Repository KTH-DD2480-Group-2/KTH-DD2480-CI-Lab-2, pull requests merged in 2021-02, with the labels that each got.

#4 #2 feat: Linked repository to Travis and add build status
  .travis.yml
  README.md
Labels: enhancement

#3 #1 docs: Add naming conventions to README.md
  README.md
Labels: documentation

#6 #5 feat: Add CI server skeleton
  .gitignore
  KTH-DD2480-CI-Lab-2.iml
  README.md
  pom.xml
  src/main/java/ContinuousIntegrationServer.java
  src/main/java/HelloWorld.java
  src/main/java/WebhookProcesser.java
  src/test/java/ContinuousIntegrationServerTest.java
  src/test/java/WebhookProcessorTest.java
Labels: ready for review

#9 #7 feat: Make the CI server fetch data from the repository
  .gitignore
  KTH-DD2480-CI-Lab-2.iml
  pom.xml
  src/main/java/ContinuousIntegrationServer.java
  src/main/java/WebhookProcesser.java
  src/test/java/ContinuousIntegrationServerTest.java
  src/test/java/InvalidGitPayload.txt
  src/test/java/ValidGitPayload.txt
  src/test/java/WebhookProcessorTest.java
Labels: ready for review

#15 #12 feat: The CI server extracts the repo zip and runs it
  buildlogs/dummy.txt
  pom.xml
  src/main/java/ContinuousIntegrationServer.java
  src/main/java/WebhookProcesser.java
  src/test/java/ContinuousIntegrationServerTest.java
  src/test/java/WebhookProcessorTest.java
Labels: ready for review

#14 #13 feat: Add skeleton for frontend CI dashboard
  .gitignore
  README.md
  pom.xml
  src/main/java/ContinuousIntegrationServer.java
  src/main/webapp/ci-frontend/.gitignore
  src/main/webapp/ci-frontend/README.md
  src/main/webapp/ci-frontend/package.json
  src/main/webapp/ci-frontend/public/favicon.ico
  src/main/webapp/ci-frontend/public/index.html
  src/main/webapp/ci-frontend/public/logo192.png
  src/main/webapp/ci-frontend/public/logo512.png
  src/main/webapp/ci-frontend/public/manifest.json
  src/main/webapp/ci-frontend/public/robots.txt
  src/main/webapp/ci-frontend/src/App.css
  src/main/webapp/ci-frontend/src/App.test.tsx
  src/main/webapp/ci-frontend/src/App.tsx
  src/main/webapp/ci-frontend/src/components/app-bar.tsx
  src/main/webapp/ci-frontend/src/components/build-status-card.tsx
  src/main/webapp/ci-frontend/src/components/build-status-timeline.tsx
  src/main/webapp/ci-frontend/src/index.css
  src/main/webapp/ci-frontend/src/index.tsx
  src/main/webapp/ci-frontend/src/logo.svg
  src/main/webapp/ci-frontend/src/model/build-status-item.ts
  src/main/webapp/ci-frontend/src/model/build-status-provider.ts
  src/main/webapp/ci-frontend/src/react-app-env.d.ts
  src/main/webapp/ci-frontend/src/reportWebVitals.ts
  src/main/webapp/ci-frontend/src/setupTests.ts
  src/main/webapp/ci-frontend/tsconfig.json
Labels: ready for review

#18 #17 fix: Fixed commit status bug and use system variables for access token
  README.md
  src/main/java/WebhookProcesser.java
Labels: ready for review

#19 #11 feat: Server collects all builds into single JSON-object
  pom.xml
  src/main/java/ContinuousIntegrationServer.java
  src/main/java/HistoryProcesser.java
  src/main/java/WebhookProcesser.java
  src/test/buildlogs/dummy.txt
  src/test/java/HistoryProcesserTest.java
Labels: feature

#21 #20 feat: Add parsing in frontend for api/history
  src/main/webapp/ci-frontend/src/App.test.tsx
  src/main/webapp/ci-frontend/src/App.tsx
  src/main/webapp/ci-frontend/src/components/build-status-card.tsx
  src/main/webapp/ci-frontend/src/components/build-status-timeline.tsx
  src/main/webapp/ci-frontend/src/model/build-status-item.test.ts
  src/main/webapp/ci-frontend/src/model/build-status-item.ts
  src/main/webapp/ci-frontend/src/model/build-status-provider.ts
  src/test/java/ContinuousIntegrationServerTest.java
Labels: ready for review

#25 #23 feat: Add build info to frontend cards
  src/main/webapp/ci-frontend/src/components/build-status-card.test.tsx
  src/main/webapp/ci-frontend/src/components/build-status-card.tsx
  src/main/webapp/ci-frontend/src/model/build-status-provider.ts
Labels: ready for review

#26 #24 feat: Add url handler for frontend
  src/main/webapp/ci-frontend/package.json
  src/main/webapp/ci-frontend/src/App.tsx
  src/main/webapp/ci-frontend/src/components/build-status-card.test.tsx
  src/main/webapp/ci-frontend/src/components/build-status-card.tsx
  src/main/webapp/ci-frontend/src/components/build-status-timeline.tsx
Labels: ready for review

#29 #28 docs: Add contributions and build links
  README.md
Labels: documentation
